"use client";
import { Mail, Phone, Shield, UserRound } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Page } from "@/components/ui/page";
import { StatusBadge } from "@/components/ui/status-badge";
import { formatDateTime, initials } from "@/lib/format";
import { useUser } from "@/modules/users/hooks/use-users";

export function UserDetailPage({ id }: { id: string }) { const query = useUser(id); if (query.isLoading) return <Page title="Chi tiết người dùng"><div className="h-64 rounded-2xl skeleton" /></Page>; if (!query.data) return <Page title="Không tìm thấy người dùng"><p className="text-danger">Không thể tải dữ liệu tài khoản.</p></Page>; const user = query.data; return <Page title="Chi tiết người dùng" description="Thông tin tài khoản và quyền truy cập Fish ERP."><div className="grid gap-5 lg:grid-cols-[320px_1fr]"><Card className="text-center"><span className="mx-auto grid size-24 place-items-center rounded-full bg-secondary text-3xl font-bold text-primary">{initials(user.displayName ?? user.email)}</span><h2 className="mt-4 text-xl font-bold">{user.displayName || user.fullName || "Chưa đặt tên"}</h2><p className="mt-1 text-sm text-muted-foreground">{user.id}</p><div className="mt-4"><StatusBadge status={user.status} /></div></Card><Card><h2 className="text-lg font-semibold">Thông tin tài khoản</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2">{[[Mail, "Email", user.email], [Phone, "Số điện thoại", user.phoneNumber], [UserRound, "Họ và tên", user.fullName || "Chưa cập nhật"], [Shield, "Vai trò", user.role]].map(([Icon, label, value]) => { const C = Icon as typeof Mail; return <div key={String(label)} className="rounded-xl bg-muted p-4"><dt className="flex items-center gap-2 text-xs font-semibold uppercase text-muted-foreground"><C className="size-4" />{String(label)}</dt><dd className="mt-2 break-all font-medium">{String(value)}</dd></div>; })}</dl><p className="mt-5 text-sm text-muted-foreground">Tạo lúc {formatDateTime(user.createdAt)} · Cập nhật {formatDateTime(user.updatedAt)}</p></Card></div></Page>; }
